baseURL = "https://colemanhaley.com/"
languageCode = "en-us"
title = "Coleman Haley"

[params]
	cutoff = 30
	author = "Coleman Haley"

# MENU CONTENTS
[menu]
	[[menu.main]]
		identifier ="homepage"
		name = "P.J.W.S."
		url = "/"
		weight = 1
		[menu.main.params]
			activename = "Home"
	[[menu.main]]
		identifier ="media"
		name = "Media"
		url = "/media/"
		weight = 2
	[[menu.main]]
		name = "About"
		url = "/about/"
		weight = 3
	[[menu.main]]
		identifier ="blog"
		name = "Contact"
		url = "/contact/"
		weight = 4
